CREATE TABLE stage.rental_stage (
    DESCRIPTION VARCHAR(255),
    CREATED_BY_ID VARCHAR(255),
    CLOSED_BY_ID VARCHAR(255),
    VEHICLE_ID VARCHAR(255),
    VEHICLE_METER_VALUE VARCHAR(255),
    VEHICLE_METER_UNIT VARCHAR(255),
    VEHICLE_METER_AT VARCHAR(255),
    CUSTOM_FIELDS VARCHAR(255),
    REPORTED_AT VARCHAR(255),
    RESOLVED_AT VARCHAR(255),
    RESOLVED_NOTE VARCHAR(255),
    STATE VARCHAR(255),
    CREATED_AT VARCHAR(255),
    UPDATED_AT VARCHAR(255)
);



ALTER TABLE stage.rental_stage
ALTER COLUMN CUSTOM_FIELDS VARCHAR(1000);

BULK INSERT stage.rental_stage
FROM 'C:\Practise\data\downloaded_file.csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2, -- skip header row
    FIELDTERMINATOR = ',', 
    ROWTERMINATOR = '\n'
);




CREATE VIEW rental_vw as 
SELECT 
    LTRIM(RTRIM(DESCRIPTION)) AS DESCRIPTION,
    LTRIM(RTRIM(CREATED_BY_ID)) AS CREATED_BY_ID,
    LTRIM(RTRIM(CLOSED_BY_ID)) AS CLOSED_BY_ID,
    LTRIM(RTRIM(VEHICLE_ID)) AS VEHICLE_ID,
    LTRIM(RTRIM(VEHICLE_METER_VALUE)) AS VEHICLE_METER_VALUE,
    LTRIM(RTRIM(VEHICLE_METER_UNIT)) AS VEHICLE_METER_UNIT,
    LTRIM(RTRIM(VEHICLE_METER_AT)) AS VEHICLE_METER_AT,
    LTRIM(RTRIM(CUSTOM_FIELDS)) AS CUSTOM_FIELDS,
    TRY_CAST(REPORTED_AT AS DATETIME) AS REPORTED_AT,
    TRY_CAST(RESOLVED_AT AS DATETIME) AS RESOLVED_AT,
    LTRIM(RTRIM(RESOLVED_NOTE)) AS RESOLVED_NOTE,
    LTRIM(RTRIM(STATE)) AS STATE,
    TRY_CAST(CREATED_AT AS DATETIME) AS CREATED_AT,
    TRY_CAST(UPDATED_AT AS DATETIME) AS UPDATED_AT
FROM (
    SELECT DISTINCT *
    FROM stage.rental_stage
) AS src
WHERE DESCRIPTION IS NOT NULL
  AND DESCRIPTION <> '';



