name: manual inputs

on:
  workflow_dispatch:

  inputs:
    number1:
       description: this is number one 
       default: 0
       required: True 
    number2:
       description: this is number two 
       default: 0
       required: True

jobs:
  addition:
    run-on: ubantu-latest
    steps:
       - name: adding
         id: sum
         run: echo "${{inputs.number1}};${{inputs.number2}} addition="
