name: Databricks SQL Syntax Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.sql'

jobs:
  sql_syntax_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install SQLFluff
        # Use the 'databricks' extra for additional support.
        run: pip install "sqlfluff[databricks]"
        
      - name: Run SQLFluff lint
        run: |
          # Use --format github-annotation-native to create inline annotations
          # for any SQL syntax errors found.
          # The `.sqlfluff` file automatically defines the dialect.
          sqlfluff lint --format github-annotation-native --verbose .
